<?php
$listDefs = array(
	'projectStatus'			=> 'projects.status',
	'taskStatus'			=> 'tasks.status',
	'staffStatus'			=> 'staff.status',
	'operationStatus'		=> 'operations.status',
	'operationShowNote'		=> 'operations.showNote',
	'studiesStatus'         => 'studies.status',
	'projectStatusOpen'		=> 'projects.status.open',
	'taskStatusOpen'		=> 'tasks.status.open',
	'staffStatusActive'		=> 'staff.status.active',
	'staffStatusInactive'   => 'staff.status.inactive',
	'operationStatusOpen'   => 'operations.status.open',
	'operationStatusClosed' => 'operations.status.closed',
	'operationShowNoteYes'  => 'operations.showNote.yes',
	'operationShowNoteNo'	=> 'operations.showNote.no',
	'studiesStatusCancelled' => 'studies.status.cancelled',
	'studiesStatusClosed'   => 'studies.status.closed',
	'studiesStatusOpen'     => 'studies.status.open',
	'studiesStatusSuspended' => 'studies.status.suspended',
	'studiesStatusWaiting'  => 'studies.status.waiting',
	'stepsTypes'			=> 'steps.types',
	'stepsTypesScriptNONE'	=> 'steps.types.none',
	'stepsTypesScriptPHP'	=> 'steps.types.php',
	'stepsTypesScriptJAVA'	=> 'steps.types.java',
	'stepsTypesScriptHTML'	=> 'steps.types.html',
	'stepsTypesScriptC	'	=> 'steps.types.c',
	'stepsTypesScriptObjectiveC'	=> 'steps.types.objectivec',
	'stepsTypesScriptRealBasic'     => 'steps.types.realbasic',
	'stepsTypesScriptSql'	        => 'steps.types.sql',
	'stepsTypesScriptXml'	        => 'steps.types.xml',
	'cashLogOperationTypes'			=> 'cashLog.operationTypes',
	'cashLogOperationTypeIncome'	=> 'cashLog.operationType.income',
	'cashLogOperationTypeOutcome'	=> 'cashLog.operationType.outcome',
	'cashLogOperationTypeClose'		=> 'cashLog.operationType.close',
	'cashLogOperationTypeMatch'		=> 'cashLog.operationType.match',

	'logType'	        => 'log.types',
	'logTypeNone'		=> 'log.type.none',
	'logTypeBasic'		=> 'log.type.basic',
	'logTypeAdvanced'	=> 'log.type.advanced',

	'stepUnitType'					        => 'stepUnit.type',
	'stepUnitTypeText'				        => 'stepUnit.type.text',
	'stepUnitTypeLongText'		            => 'stepUnit.type.longtext',
	'stepUnitTypeInteger'			        => 'stepUnit.type.integer',
	'stepUnitTypeFloat'				        => 'stepUnit.type.float',
	'stepUnitTypeBoolean'		    	    => 'stepUnit.type.boolean',
	'stepUnitTypeList'		    		    => 'stepUnit.type.list',
	'stepUnitTypeImage'			    	    => 'stepUnit.type.image',
	'stepUnitTypeDate'			    	    => 'stepUnit.type.date',
	'stepUnitTypeSeleniumResult'	        => 'stepUnit.type.seleniumResult',
	'stepUnitTypeSeleniumResultDescription'	=> 'stepUnit.type.seleniumResultDescription',

	'operationPayment'		      => 'operations.payment',
	'operationPaymentCash'	      => 'operations.payment.cash',

	'configurationModuleHTMLModuleWebbrowser'  => 'configuration.module.HTMLModule.webbrowser',

	'triggerTypes'                  => 'trigger.types',
	'triggerTypeUrl'                => 'trigger.type.url',
	'triggerTypeSchedule'           => 'trigger.type.schedule',
	'triggerTypeQR'                 => 'trigger.type.qr',
	'triggerTypeCreateItem'         => 'trigger.type.create.item',
	'triggerTypeUpdateItem'         => 'trigger.type.update.item',
	'triggerTypeDeleteItem'         => 'trigger.type.delete.item'
);
