openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'RSM API 2.0'
  description: OpenAPI definition for RSM V2 endpoints
servers:
    - url: http://localhost:81/RSM-Core/server/htdocs/AppController/commands_RSM/api/v2
paths:
  /itemType/{itemTypeId}/item/{itemId}:
    $ref: './paths/item.yml'
  /{itemTypeId}/{itemId}:
    $ref: './paths/item.yml'
  /item/{itemId}:
    $ref: './paths/updateItem.yml'
  /item : 
    $ref: './paths/createItem.yml'
  /items:
    $ref: './paths/getItems.yml'
components:
  schemas:
    item:
      $ref: './schemas/item.yml'
    message:
      $ref: './schemas/message.yml'
    createItem: 
      $ref: './schemas/createItem.yml'